# Generated by Django 4.2.30 on 2026-05-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='location',
            field=models.CharField(blank=True, help_text='Location text or Google Maps URL', max_length=500, null=True),
        ),
    ]
